[env]
TERM = "alacritty"

[window]
padding = { x = 10, y = 10 }
startup_mode = "Maximized"
decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "ExtraLight" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "VictorMono Nerd Font", style = "Italic" }
size = 16

# Monokai Pro (Spectrum Filter)
[colors.primary]
background = "0x222222"
foreground = "0xf7f1ff"

[colors.normal]
black = "0xbab6c0"
red = "0xfc618d"
green = "0x7bd88f"
yellow = "0xfce566"
blue = "0xfd9353"
magenta = "0x948ae3"
cyan = "0x5ad4e6"
white = "0xf7f1ff"
