#!/bin/bash

# creates a new directory and changes to that directory

# check if directory name is provided
if [ $# -eq 0 ]; then
  # ask for name of directory
  read -r -p "Enter name of directory: " name
else
  name=$1
fi

# check if directory exists relative to current directory
if [ -d "$name" ]; then
  echo "Directory already exists"
  exit 1
fi

mkdir -p "$name" && cd "$name" || exit
